# Generated by Django 4.2 on 2024-01-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отрасль')),
                ('prototype_status', models.CharField(blank=True, choices=[('Yes', 'Есть'), ('No', 'Нет')], default='No', max_length=90, null=True, verbose_name='Статус прототипа')),
                ('is_allowed', models.BooleanField(verbose_name='Принят | Отказано')),
                ('development_stage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Этап развития')),
                ('additional_files', models.FileField(blank=True, null=True, upload_to='media/startup_files/', verbose_name='Дополнительные файлы')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
