# Generated by Django 4.2 on 2024-01-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя инвестора')),
                ('investment_area', models.CharField(max_length=100, verbose_name='Область инвестирования')),
                ('investment_size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер инвестиций')),
                ('additional_files', models.FileField(blank=True, null=True, upload_to='media/investor_files/', verbose_name='Дополнительные файлы')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
            },
        ),
    ]
